- name: Check for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: kubeadm join
  command: "{{ hostvars[groups.master[0]]['joincommand'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when:
    - state == "present"
    - kubelet_conf.stat.exists == False

- name: Run kubeadm reset (on destroy)
  command: "kubeadm reset --force"
  when: state == "absent"
  ignore_errors: True

# For some reason "kubeadm join" does not write the correct value here
- name: HACK - replace --network-plugin=cni with --network-plugin=kubenet
  replace:
    path: /var/lib/kubelet/kubeadm-flags.env
    regexp: network-plugin=cni
    replace: "network-plugin=kubenet"
  notify:
    - Restart kubelet
  when: state == "present"
