- name: kubectl apply dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml

- name: copy manifests
  copy:
    src: "{{ role_path }}/files/manifests/"
    dest: "/home/ubuntu/manifests/"

- name: Retrieve service catalog
  delegate_to: localhost
  os_auth:

- name: Upload webook kubeconfig file
  template:
    dest: /home/ubuntu/manifests/k8s-keystone-auth.yaml
    src: "{{ role_path }}/templates/k8s-keystone-auth.yaml.j2"

- name: kubectl apply admin-user for dashboard
  command: kubectl apply -f /home/ubuntu/manifests/admin-user.yaml

- name: Install helm
  include: helm.yaml

- name: Install NGINX ingress
  include: nginx-ingress.yaml

- name: copy syncconfig.yaml
  become: true
  copy:
    src: "{{ role_path }}/files/syncconfig.yaml"
    dest: "/etc/kubernetes/syncconfig.yaml"

- name: kubectl apply k8s-keystone-auth
  command: kubectl apply -f /home/ubuntu/manifests/k8s-keystone-auth.yaml

# Default storage class
- name: Label nodes with availability zone {{ availability_zone }}
  # cf. https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
  command: "kubectl label  --overwrite=true nodes {{ nodes_name }}{{ item }} failure-domain.beta.kubernetes.io/zone={{ availability_zone }}"
  with_sequence: count={{ nodes_count }}

- name: Copy default storage class configuration
  template:
    src: "{{ role_path }}/templates/default-storage-class.yaml.j2"
    dest: /home/ubuntu/manifests/default-storage-class.yaml

- name: Apply default storage class
  command: kubectl apply -f /home/ubuntu/manifests/default-storage-class.yaml
# End: Default storage class
